# Numpy Array

In [4]:
import numpy as np

In [2]:
lista = [1,2,3,4,5,6]
lista

[1, 2, 3, 4, 5, 6]

In [3]:
arr = np.array(lista)
arr

array([1, 2, 3, 4, 5, 6])

In [4]:
type(arr)

numpy.ndarray

In [5]:
matriz =[[1,2,3],[4,5,6],[7,8,9]]
matriz = np.array(matriz)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
arr[0] + arr[5]

7

In [7]:
matriz[0]

array([1, 2, 3])

In [8]:
matriz[0,2]

3

In [9]:
matriz[0][2]

3

In [10]:
arr[1:6]

array([2, 3, 4, 5, 6])

In [11]:
arr[:6]

array([1, 2, 3, 4, 5, 6])

In [12]:
arr[::3]

array([1, 4])

In [13]:
arr[-1]

6

In [14]:
arr[-3:]

array([4, 5, 6])

In [15]:
matriz[1:]

array([[4, 5, 6],
       [7, 8, 9]])

In [16]:
matriz[1:,0:2]


array([[4, 5],
       [7, 8]])

In [17]:
matriz3=[[[1,2],[3,4]],[[5,6],[7,8]]]

In [18]:
matriz3=np.array(matriz3)

In [19]:
matriz3[0,1]

array([3, 4])

In [20]:
matriz3[0,1,1]


4

# Tipos de Datos Numpy

In [21]:
a=[1,2,3,4]


In [30]:
arr=np.array(a)
arr.dtype

dtype('int64')

In [28]:
arr=np.array(a, dtype='float64')
arr.dtype

dtype('float64')

In [29]:
arr

array([1., 2., 3., 4.])

In [31]:
# arr=np.array(a)
arr=arr.astype(np.float64)
arr

array([1., 2., 3., 4.])

In [32]:
arr=np.array([0,1,2,3])
arr=arr.astype(np.bool_)
arr

array([False,  True,  True,  True])

In [33]:
arr=np.array([0,1,2,3])
arr=arr.astype(np.string_)
arr

array([b'0', b'1', b'2', b'3'], dtype='|S21')

In [34]:
arr=np.array(['0','1','2','3'])
arr=arr.astype(np.int8)
arr

array([0, 1, 2, 3], dtype=int8)

[Data Types](https://numpy.org/doc/stable/user/basics.types.html)

# Dimensiones

In [35]:
scalar = np.array(42)
print(scalar)

42


In [37]:
scalar.ndim

0

In [38]:
vector = np.array([2,3,4])
print(vector)
vector.ndim

[2 3 4]


1

In [39]:
matriz = np.array([[2,3,4],[5,6,7]])
print(matriz)
matriz.ndim

[[2 3 4]
 [5 6 7]]


2

In [40]:
tensor = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]],[[13, 13, 15], [16, 17, 18], [19, 20, 21], [22, 23, 24]]])
print(tensor)
tensor.ndim

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 13 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]]


3

### Agregar o eliminar dimensiones

In [42]:
vector = np.array([2,3,4],ndmin=10)
print(vector)
vector.ndim

[[[[[[[[[[2 3 4]]]]]]]]]]


10

In [44]:
expand=np.expand_dims(np.array([2,3,4]),axis=0)
print(expand)
expand.ndim

[[2 3 4]]


2

In [46]:
print(vector, vector.ndim)
vector_2=np.squeeze(vector)
print(vector_2,vector_2.ndim)

[[[[[[[[[[2 3 4]]]]]]]]]] 10
[2 3 4] 1


# Creando Arrays

In [47]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [48]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [51]:
np.zeros(3)

array([0., 0., 0.])

In [52]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [53]:
np.ones((10,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [55]:
np.linspace(0,10,11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [56]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [57]:
np.random.rand()

0.6538435804804508

In [58]:
np.random.rand(4)


array([0.66092989, 0.08414666, 0.55570904, 0.50917496])

In [59]:
np.random.rand(4,4)


array([[0.34699924, 0.9077447 , 0.39779101, 0.42633128],
       [0.80668806, 0.20899176, 0.0601301 , 0.75092175],
       [0.37086739, 0.64197828, 0.26590275, 0.53069265],
       [0.62099065, 0.95708336, 0.72126737, 0.37423824]])

In [60]:
np.random.randint(1,15)

11

In [61]:
np.random.randint(1,100,(10,10))


array([[39, 84, 89, 12, 86, 15, 97, 55, 99, 37],
       [55, 33, 23, 91, 41, 78, 26, 67, 24, 78],
       [85, 68,  9, 27, 55, 24, 35, 79,  6, 39],
       [22, 94, 90,  5, 12, 40, 18, 46, 44, 88],
       [77, 37, 96, 68, 20, 84, 46, 17, 73, 65],
       [92, 25, 36,  1, 52, 47, 42, 97, 89, 48],
       [66,  6, 13, 94, 26, 53, 64, 21, 53, 82],
       [45, 37, 20, 40, 78, 16, 26, 19, 15,  4],
       [14, 27,  6, 96, 65, 30, 89, 17, 81, 81],
       [63, 51, 63, 15, 94, 91, 30, 47, 81, 43]])

# Shape & Reshape

In [62]:
arr=np.random.randint(1,10,(3,2))

In [63]:
arr.shape

(3, 2)

In [64]:
arr.reshape(1,6)

array([[7, 2, 1, 3, 1, 2]])

In [65]:
arr.reshape(2,3)

array([[7, 2, 1],
       [3, 1, 2]])

In [66]:
np.reshape(arr,(1,6))

array([[7, 2, 1, 3, 1, 2]])

In [67]:
arr


array([[7, 2],
       [1, 3],
       [1, 2]])

In [70]:
np.reshape(arr,(2,3),'C')

array([[7, 2, 1],
       [3, 1, 2]])

In [71]:
np.reshape(arr,(2,3),'F')


array([[7, 1, 3],
       [1, 2, 2]])

In [72]:
np.reshape(arr,(2,3),'A')


array([[7, 2, 1],
       [3, 1, 2]])

In [74]:
np.reshape(np.arange(0,15),(3,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [77]:
np.reshape(np.linspace(0,14,15),(3,5))


array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.]])

# Funciones principales de NumPy

In [2]:
arr=np.random.randint(1,20,10)
arr

NameError: name 'np' is not defined

In [79]:
matriz=arr.reshape(2,5)
matriz

array([[ 2,  4, 19,  9, 15],
       [ 2, 12, 17, 13, 19]])

In [81]:
arr.max()

19

In [82]:
matriz.max()

19

In [83]:
matriz.max(1)

array([19, 19])

In [84]:
matriz.max(0)


array([ 2, 12, 19, 13, 19])

In [85]:
arr.argmax()

6

In [1]:
arr

NameError: name 'arr' is not defined

In [87]:
matriz.argmax(1)

array([2, 4])

In [88]:
arr.min()

1

In [89]:
matriz.min(0)

array([ 2,  4, 17,  9, 15])

In [90]:
arr.ptp()

18

In [91]:
matriz.ptp(0)

array([0, 8, 2, 4, 4])

In [93]:
np.percentile(arr,50)

7.0

In [96]:
arr.sort()
arr

array([ 1,  1,  3,  3,  7,  7, 12, 17, 19, 19])

In [97]:
np.median(arr)

7.0

In [98]:
np.median(matriz,0)

array([ 2.,  8., 18., 11., 17.])

In [99]:
matriz

array([[ 2,  4, 19,  9, 15],
       [ 2, 12, 17, 13, 19]])

In [100]:
np.std(arr)

6.9346953790343235

In [101]:
np.var(arr)


48.089999999999996

In [102]:
np.std(arr)**2


48.09

In [103]:
np.mean(arr)

8.9

In [105]:
a=np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [117]:
b=np.array([5,6])


In [107]:
np.concatenate((a,b), axis=0)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [110]:
a.ndim

2

In [118]:
b.ndim

1

In [119]:
b=np.expand_dims(b,axis=0)
b

array([[5, 6]])

In [112]:
np.concatenate((a,b), axis=0)


array([[1, 2],
       [3, 4],
       [5, 6]])

In [113]:
np.concatenate((a,b), axis=1)


ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

In [115]:
np.concatenate((a,b.T), axis=1)


array([[1, 2, 5],
       [3, 4, 6]])

[Statistical functions](https://numpy.org/doc/stable/reference/routines.statistics.html)

[Mathematical functions](https://numpy.org/doc/stable/reference/routines.math.html)


# Copy

In [120]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [121]:
trozo_de_arr=arr[0:6]

In [122]:
trozo_de_arr[:]=0
trozo_de_arr

array([0, 0, 0, 0, 0, 0])

In [123]:
arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

In [128]:
arr_copy=arr.copy()

In [125]:
arr_copy

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

In [129]:
arr_copy[:]=100

In [130]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [131]:
arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

# Condiciones

In [132]:
arr=np.linspace(1,10,10, dtype='int8')
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

In [135]:
indices_cond= arr > 5
indices_cond

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [136]:
arr[indices_cond]

array([ 6,  7,  8,  9, 10], dtype=int8)

In [138]:
arr[(arr>5) & (arr<9)]


array([6, 7, 8], dtype=int8)

In [139]:
arr[(arr>5)]=99


In [140]:
arr

array([ 1,  2,  3,  4,  5, 99, 99, 99, 99, 99], dtype=int8)

In [142]:
arr[arr==99]

array([99, 99, 99, 99, 99], dtype=int8)

In [143]:
arr_2=np.linspace(1,20,20, dtype='int8')
arr_2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20], dtype=int8)

In [145]:
arr_2[arr_2%2==0]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20], dtype=int8)

# Operaciones

In [146]:
lista=[1,2]
lista

[1, 2]

In [147]:
lista * 2

[1, 2, 1, 2]

In [148]:
arr=np.arange(0,10)
arr2= arr.copy()

In [150]:
arr*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [151]:
arr+2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [152]:
1/arr

/tmp/ipykernel_819/255282349.py:1: RuntimeWarning: divide by zero encountered in true_divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [153]:
arr**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [154]:
arr+arr2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [155]:
arr*arr2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [156]:
matriz=arr.reshape(2,5)
matriz2=matriz.copy()

In [157]:
matriz

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [158]:
matriz*matriz2

array([[ 0,  1,  4,  9, 16],
       [25, 36, 49, 64, 81]])

In [159]:
np.matmul(matriz,matriz2.T)

array([[ 30,  80],
       [ 80, 255]])

In [160]:
matriz @ matriz2.T

array([[ 30,  80],
       [ 80, 255]])

[Basic Array Operations](https://numpy.org/doc/stable/user/absolute_beginners.html#basic-array-operations)

In [5]:
np.array(['hola','2','4','5'],dtype='float64')

ValueError: could not convert string to float: 'hola'

In [7]:
arr = np.array([13, 6, 3, 5, 10])

In [9]:
np.max(arr)

13